### ISSUE TITLE
How to make a local HotkeyManager

### ISSUE THREAD

**Issue by raytangRT** [thomaslevesque/NHotkey#11]
Hi, 

I am trying to use your library to implement a set of Hotkeys, but I am encountering a problem.

My application contains 2 windows, namely Window A and Window B, and Window A and Window B have a different set of hotkeys, which some of them might be overlapping.

My question is how to implement or config NHotkey to execute hotkeys based on focused windows. 

Thanks.

**Comment by thomaslevesque** [comment]
Hi @raytangRT,

The whole point of NHotkey is to implement _global_ hotkeys, so by definition they can't be local to a window... You should use the native hotkey mechanism for the technology you're using (WPF or Windows Forms) instead.

**Comment by raytangRT** [comment]
@thomaslevesque 

Thanks for the quick reply, 

my application requires both global and local hotkeys, and I may try to manually unregister the hotkeys on focus, and re-register when lost focus.

Thanks again.
