### ISSUE TITLE
How i can SendKeys to window, without infinity iteration?

### ISSUE THREAD

**Issue by MairwunNx** [thomaslevesque/NHotkey#13]
I use your beautiful library, but, when i check clicking on e.g F9, and Send key to another window (e.g F9) - i get infinity iteration :D

i.e if i click F9 and if i send key F9 i get infinity iteration. 

```
                if (e.Name == "F9")
                {
                    IntPtr sacredhandle = FindWindow("Sacred", "Sacred");

                    SetForegroundWindow(sacredhandle);

                    SendKeys.SendWait(HotkeySettings.GameHotkeySettings.KeyF9); // e.g F9 

                    AppLogger.Log.Info($"Key {HotkeySettings.GameHotkeySettings.KeyF9} successfully sended to Sacred.exe window");

                    e.Handled = true;
                }
```

or : if i click on Z (Z emulate clicking F9), - i also get infinity iteration.

```
                if (e.Name == "Z")
                {
                    IntPtr sacredhandle = FindWindow("Sacred", "Sacred");

                    SetForegroundWindow(sacredhandle);

                    SendKeys.SendWait(HotkeySettings.GameHotkeySettings.KeyZ); // e.g also F9 

                    AppLogger.Log.Info($"Key {HotkeySettings.GameHotkeySettings.KeyZ} successfully sended to Sacred.exe window");

                    e.Handled = true;
                }
```
Also clicking on Z, lib think what i clicking on F9, and ... infinity iteration :D

**Comment by thomaslevesque** [comment]
OK, so you intercept a key, then send the same key to another app via `SendKeys`? This can't work, because the key will be intercepted again. It might be possible if you send a different key to the other application (one you don't intercept).

**Comment by MairwunNx** [comment]
I solved problem, replaced SendKeys.SendWait(...) on 

                    const int WM_KEYDOWN = 0x0100;

                    IntPtr hWndNotepad = NativeMethods.FindWindow("Sacred", null);

                    NativeMethods.PostMessage(hWndNotepad, WM_KEYDOWN, Keys.I, IntPtr.Zero);

You can close it issue. I think, it code ↑ may help to someone. Thanks for your comment!
