### ISSUE TITLE
Assemblies are not Strong Named

### ISSUE THREAD

**Issue by maggarwal** [thomaslevesque/NHotkey#14]
Hi,

I am unable to use this library as it is not strong named. Is it possible for you to publish a strong named version or strong name the package by default?

**Comment by thomaslevesque** [comment]
Hi @maggarwal,

For a while, the consensus in the C# OSS community was to *not* strong-name assemblies, so I didn't. However, this seems to have changed; Microsoft now [recommends strong-naming open-source libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming). So I think I will do so at some point, but it won't happen overnight.

In the meantime, you can use https://github.com/brutaldev/StrongNameSigner to strong-name third-party assemblies yourself.

**Comment by thomaslevesque** [comment]
Adding this to vNext milestone. I've started strong-naming some of my libraries a while ago, and I see no reason not to do it for this one.

**Comment by thomaslevesque** [comment]
This is fixed in [2.0.0-beta.1](https://github.com/thomaslevesque/NHotkey/releases/tag/2.0.0-beta.1)
