### ISSUE TITLE
Trigger callback on Key-Up not Key-Down

### ISSUE THREAD

**Issue by skjerns** [thomaslevesque/NHotkey#17]
(linking https://github.com/jjw24/Wox/issues/138)

Is there any way to set the trigger of a hotkey message on key-up instead of key-down using `nhotkey`?

**Comment by thomaslevesque** [comment]
Hi @skjerns,

Unfortunately, it's not possible. NHotkey relies on the [`RegisterHotKey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) Win32 API, which doesn't give control over this.
