### ISSUE TITLE
shortcut of win key + regular key throw exception

### ISSUE THREAD

**Issue by eladpotok** [thomaslevesque/NHotkey#21]
I am trying to register to the hotkey with Key (for example) 'Z' and modifier as "Windows" .
When I register for the first time, I get this exception:

NHotkey.HotkeyAlreadyRegisteredException: 'Hot key is already registered. (Exception from HRESULT: 0x80070581)'

Inner exception:
COMException: Hot key is already registered. (Exception from HRESULT: 0x80070581)

Windows with other modifier (for instance; ctrl+windows+z) works fine.

This is WPF application.

**Comment by thomaslevesque** [comment]
Hi @eladpotok,

The Windows key modifier is reserved by the operating system, so you can't use it for your own hotkeys. This is a restriction of the [RegisterHotKey](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) API, on which NHotkey relies:

> MOD_WIN 0x0008
> Either WINDOWS key was held down. These keys are labeled with the  Windows logo. **Keyboard shortcuts that involve the WINDOWS key are  reserved for use by the operating system**.

However, even though it's not clearly mentioned in the docs, you *can* combine the Windows modifier with another modifier (Control, Alt or Shift). So you can't use Win+Z., but you can use Control+Win+Z or Shift+Win+Z.

**Comment by eladpotok** [comment]
Ok, Thank you for clarifying. you can close the issue.

**Comment by stnkl** [comment]
I tried registering hotkeys including the Windows key and discovered that explorer.exe actually registers most of them resulting in a `HotkeyAlreadyRegisteredException`. You can work around this by killing explorer.exe, registering your hotkey and restarting explorer.exe afterwards. So this is not exactly a restriction of the WinAPI but rather a system application stealing hotkeys.
