### ISSUE TITLE
PTT (Press To Talk) function?

### ISSUE THREAD

**Issue by e4rthdog** [thomaslevesque/NHotkey#23]
I need to implement a PTT Press To Talk , function in my app..

That is i need to do something while the key is pressed. Is there any way to do that with this library?

As i see the library is detecting the key when it is released. 

Any ideas?

**Comment by thomaslevesque** [comment]
Hi @e4rthdog,

> As i see the library is detecting the key when it is released.

Actually, it calls the handler when the key is pressed. After a short delay, if the key is still pressed, the handler is called repeatedly until the key is released.

This behavior is inherited from the [`RegisterHotKey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) Windows API, of which NHotkey is just a wrapper. So, NHotkey won't let you distinguish between "key down" and "key up".

However, you can easily use the `KeyDown` and `KeyUp` events in a WPF or WinForms application. If you need the hotkey to be global (i.e. work even if your app doesn't have focus), you'll probably need to use low level keyboard hooks (See [`SetWindowsHookEx`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexw) with the `WH_KEYBOARD_LL` hook)

**Comment by e4rthdog** [comment]
> Hi @e4rthdog,
> 
> > As i see the library is detecting the key when it is released.
> 
> Actually, it calls the handler when the key is pressed. After a short delay, if the key is still pressed, the handler is called repeatedly until the key is released.
> 
> This behavior is inherited from the [`RegisterHotKey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) Windows API, of which NHotkey is just a wrapper. So, NHotkey won't let you distinguish between "key down" and "key up".
> 
> However, you can easily use the `KeyDown` and `KeyUp` events in a WPF or WinForms application. If you need the hotkey to be global (i.e. work even if your app doesn't have focus), you'll probably need to use low level keyboard hooks (See [`SetWindowsHookEx`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexw) with the `WH_KEYBOARD_LL` hook)

I see. Do you think that using a timer with `GetAsyncKeyState `is an overkill? I'd rather keep off the low level hooks as they can make antivirus programs think that the app is a keylogger..

**Comment by thomaslevesque** [comment]
I'm not familiar with `GetAsyncKeyState`, but from what I just read, I guess that could work.

**Comment by Lakritzator** [comment]
Like @thomaslevesque said, if you want to handle key up/down when your application is NOT active, your can use low level hooks. But if it makes sense to get the key information while the application is active, you don't need other solutions and use the build in WPF or Forms  functionality.

If however you want to handle low level key, try one of my projects I wrote for Greenshot, they are combined here:
https://github.com/dapplo/Dapplo.Windows

There is a nuget package for keyboard handling: https://www.nuget.org/packages/Dapplo.Windows.Input

This provides a low level keyboard hook, and uses observables to make your code easier.
It takes care of registering and unregistering and has a foundation to handle different key combinations.

I never tried it, but this might work... Let's say you want to have the key combination Shift + T to trigger the talk.

```
var keyHandler = new KeyCombinationHandler(VirtualKeyCode.Shift, VirtualKeyCode.KeyT);
var subscription = KeyboardHook.KeyboardEvents.Where(sequenceHandler).Subscribe(args =>
{
   if (args.IsKeyDown)
   {
       // Talk
   }
   else
   {
      // Stop
   }
});

// finished?
subscription.Dispose();
```

If you try using it and something doesn't work, write an issue in the repository.

**Comment by e4rthdog** [comment]
Thank you very much. I have enough things to try.

**Comment by e4rthdog** [comment]
> Like @thomaslevesque said, if you want to handle key up/down when your application is NOT active, your can use low level hooks. But if it makes sense to get the key information while the application is active, you don't need other solutions and use the build in WPF or Forms functionality.
> 
> If however you want to handle low level key, try one of my projects I wrote for Greenshot, they are combined here:
> https://github.com/dapplo/Dapplo.Windows

I will definately look into Dapplo for other projects also! Thanks for bringing that to my attention.

Indeed i need to handle the key while the application is out of focus.

The use case here is that , lets say you are a streamer and you are stresming an app that has PTT funcitonality. You want to have music loud while you DONT speak ,but you need the volume to go down when you press your PTT and talk.

My app will handle the same PTT as your streaming app and will bring the volume down on specific apps  you define , while you talk. After you release the key , the volume will return back to normal.

So i will try with the timer and the GetAsyncKeyState which is an api call to get the key state in realtime.

If that fails i will see the low level hook which i want to avoid for false antivirus alarms.

Thanks
