### ISSUE TITLE
Add a global enable/disable setting

### ISSUE THREAD

**Issue by thomaslevesque** [thomaslevesque/NHotkey#24]
Add a `IsEnabled` setting on `HotkeyManager` to be able to suspend event processing.

Prompted by https://github.com/thomaslevesque/blog/issues/6#issuecomment-640182883

**Comment by thomaslevesque** [comment]
@misbah-rehman, I added this feature in a new 2.1.0 release

**Comment by misbah-rehman** [comment]
Thanks Thomas,

**Comment by hutum** [comment]
Hi Thomas, 
I would like to thank you for your effort in using global hotkey in WPF.
I have been struggling to re-register a new hotkey.
You mentioned here [https://github.com/thomaslevesque/NHotkey](url)
that HotkeyManager.RegisterGlobalHotkey needs to be set false to do this.
But I'm getting error "HotkeyManager does not contain a definition for RegisterGlobalHotkey" when I'm trying to set it to false.
What am I doing wrong?
I would really appreciate if you could guide me on this.
Thanks again.

**Comment by thomaslevesque** [comment]
@hutum `HotkeyManager.RegisterGlobalHotkey` is a WPF attached property, which is usually set in XAML. To set it from C# code, you need to use `HotkeyManager.SetRegisterGlobalHotkey(target, false)` (where `target` is the `KeyBinding` object). To get the key binding, assuming you're in the Window's code-behind, you can do something like this:

```csharp
var keyBinding = this.InputBindings
    .OfType<KeyBinding>()
    .First(kb => kb.Key == Key.N && kb.Modifiers == (ModifierKeys.Control | ModifierKeys.Alt));

HotkeyManager.SetRegisterGlobalHotkey(keyBinding, false);
```

Of course, it's not very convenient... The KeyBinding approach is the the simplest, but it's not great if you intend to change the hotkeys at runtime. In that scenario, it's probably best to use `HotkeyManager.Current.AddOrReplace` directly.

**Comment by hutum** [comment]
Thanks a lot Thomas for responding so quickly.
Allow me to give you a clear picture on what I am trying to achieve.
I have an UWP app which communicates with a WPF app through AppService.
