### ISSUE TITLE
storing keys in xml settings file

### ISSUE THREAD

**Issue by jfayre** [thomaslevesque/NHotkey#27]
Hello!
Do you have any code examples for reading/writing hotkey values from a .net settings file? Just not sure how to best represent them in the file, then read them in and register them when the app starts. I was initially using WPF, but I've since switched to Winforms for various reasons. 
Thanks!

**Comment by thomaslevesque** [comment]
Hi @jfayre,

This is a bit off topic for this project... You'd better ask on StackOverflow.
Anyway, I don't have an answer specifically for XML settings files, but you can just represent the hotkeys as strings like "Ctrl+A", and use [`KeysConverter`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keysconverter?view=netcore-3.1) to convert them to  `Keys`.

**Comment by jfayre** [comment]
Never mind, I figured it out. In the settings file, set the type to System.Windows.Forms.Keys, then put a comma between each key.
