### ISSUE TITLE
Cannot add F12 as hotkey without modifiers

### ISSUE THREAD

**Issue by DrCopyPaste** [thomaslevesque/NHotkey#28]
Using NHotkey.Wpf I cannot add F12 as a hotkey without modifiers. If I try I get NHotkey.HotkeyAlreadyRegisteredException: 'Hot key is already registered.

While this works:
`HotkeyManager.Current.AddOrReplace("Increment", new KeyGesture(Key.F12, ModifierKeys.Alt), OnIncrement);`

This throws the exception:
`HotkeyManager.Current.AddOrReplace("Increment1", new KeyGesture(Key.F12, ModifierKeys.None), OnIncrement);`
throws exception

And even more confusing, this works too:
`HotkeyManager.Current.AddOrReplace("Increment2", new KeyGesture(Key.F11, ModifierKeys.None), OnIncrement);`

I expected (maybe I am mistaken) that if defining a KeyGesture for a Key (with or without modifiers) is legal, setting it as a hotkey should be, too.

**Comment by thomaslevesque** [comment]
Hi @DrCopyPaste,

In general, it's not possible to register a hotkey without a modifier key; it's a restriction of the [RegisterHotKey](https://docs.microsoft.com/fr-fr/windows/win32/api/winuser/nf-winuser-registerhotkey) Win32 API. There seems to be a few exceptions, e.g. for function keys, but it's not clearly documented.

As for F12, the documentation explicitly states:

> The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident.

So you can never register F12 as a hotkey.

I should probably document the limitations... I'll create an issue for this.

**Comment by DrCopyPaste** [comment]
OK, thx for the answer, could this be another exception though? "already added" is really confusing., And is there an easier way to probe WHETHER a hotkey is assignable?

I used to do a try catch on creating an instance of a KeyGesture, now I would have to include adding a dummy hotykey and instantly removing it just to test whether it is legal.

**Comment by thomaslevesque** [comment]
> could this be another exception though? "already added" is really confusing.

Not easily... This is the error message returned by Windows itself, I don't have any more details to provide a better message.

> And is there an easier way to probe WHETHER a hotkey is assignable?

Not that I know of. Windows doesn't provide any API for this, unfortunately.

Keep in mind that `NHotkey` is just a wrapper about a Win32 API; it can't do anything that the Win32 API can do...
