### ISSUE TITLE
how to not Disable System Work

### ISSUE THREAD

**Issue by GihanSoft** [thomaslevesque/NHotkey#30]
I set an hot key on space (and other keys) and every now space works nowhere. how to make it work in other programs?
(I use NHotKey for a trick. to get keys while focused on VLC video view.)
I disabled hotkey action in my app with checking window.IsActive but I want keys work else where.
```csharp
IntPtr activeWinHwnd = GetActiveWindow();
Window win = Window.GetWindow(this);
Window win2 = Window.GetWindow(InPlayerBrd);
if (!win.IsActive && !win2.IsActive && activeWinHwnd != MediaPlayer.Hwnd)
    return;
```

**Comment by thomaslevesque** [comment]
Hi @GihanSoft,

Sorry, I'm not sure I understand your exact problem... I'll answer what I can.

You can't register the Space key alone as a hotkey, you need to register it with at least one modifier key. That's a limitation of the RegisterHotkey Win32 that is used by NHotkey. The only way to catch a key without a modifier would be to use a low-level hook; NHotkey can't help you there.

I'm not sure what is the code that you posted; it doesn't seem related to hotkey handling.

**Comment by GihanSoft** [comment]
I did set space and m hotkey without modifier with add or replace method.
But I found out what I need is hwndSource hook.
Thank you anyway. I really like your package and I like that you answered me fast.
Thanks.
