### ISSUE TITLE
Single Press

### ISSUE THREAD

**Issue by Yanik39** [thomaslevesque/NHotkey#37]
Hi,

I have registered Alt A perfectly.
But when i press alt-a, that hotkey function runs many times if i press little longer.

Is there a way to handle hotkey once? I mean keeping pressed to alt-a should run handler function just once.

Thanks

**Comment by thomaslevesque** [comment]
Hi @Yanik39,

`HotKeyManager.AddOrReplace` has an overload with a `noRepeat` parameter. Just pass true for this parameter to suppress the repeat behavior.

**Comment by thomaslevesque** [comment]
Glad you were able to resolve it!
