### ISSUE TITLE
NHotkey doesn't have Mouse support

### ISSUE THREAD

**Issue by Pyperdok** [thomaslevesque/NHotkey#38]
NHotkey uses System.Windows.Input.Key enum. Why don't we do mouse supporting?
For example we can use Enum, because it is parent class of these enums:
Enum <- System.Windows.Input.Key
Enum <- System.Windows.Input.MouseButton
and WinAPI supports mouse buttons. See: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by CheemsForChips** [comment]
so hhow can i do to add Mouse support???Can you give me some advise

**Comment by thomaslevesque** [comment]
Hi @CheemsForChips,

As I mentioned before, I don't think that's possible. I should have closed this issue, will do so now.

As for supporting global mouse events, you can do it using low-level mouse hooks, but I think it's far from trivial... Anyway, I have no intention of supporting that in this library.
