### ISSUE TITLE
Please don't make the HotkeyEventArgs's constructor internal

### ISSUE THREAD

**Issue by ihsansfd** [thomaslevesque/NHotkey#39]
I'm about to unit test this class until I know that the HotkeyEventArg's constructor is set to internal. This makes it such a pain to unit test. Please fix this. Or at the very least if you still want to make it internal, provide public factory that everyone can access.

Btw, great library!

**Comment by thomaslevesque** [comment]
Hi @ihsansfd,
Thanks for the feedback!
Not sure why the constructor is internal, there's no good reason for it. I'll merge your PR.

**Comment by thomaslevesque** [comment]
I just released a new version (2.1.1) with the change, it should be available on NuGet shortly.

**Comment by ihsansfd** [comment]
Thanks for the support
