### ISSUE TITLE
How to conditionally handle key

### ISSUE THREAD

**Issue by dax0** [thomaslevesque/NHotkey#4]
I've tried setting .Handled = false but it doesn't seem to have any effect.  I would like to only intercept the hotkey if certain conditions are met.  Not sure if this is even possible with WinAPI, any help would be appreciated thanks

**Comment by thomaslevesque** [comment]
Setting `Handled` to true just suppresses the default WndProc handling for the WM_HOTKEY message.

What exactly are you trying to do? If you want the key to not be considered a hotkey, I don't think that's possible.

**Comment by dax0** [comment]
I actually thought you could choose to not handle a hotkey conditionally with winapi but it looks like you can't. I'm working around this by unregistering and registering the hotkeys when I want them to be enabled, which your library makes it easy to do.  Thanks!
