### ISSUE TITLE
Override already existing hotkey?

### ISSUE THREAD

**Issue by colinwurtz** [thomaslevesque/NHotkey#5]
Is there a way to override a global hotkey that is already registered in the system? For example, if I wanted to change Ctrl + V to something else that I handle in code would I be able to do that somehow?

**Comment by thomaslevesque** [comment]
No, I don't think it's possible. The [`RegisterHotKey`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309%28v=vs.85%29.aspx) function doesn't allow it:

> RegisterHotKey fails if the keystrokes specified for the hot key have already been registered by another hot key.

**Comment by colinwurtz** [comment]
I guess I might have to resort to using hooks. Autohotkey allows the system level override (not exactly sure how the language does this) and I'm trying to port an existing AHK application to C#. Probably outside your scope of this project to offer that alternative. Thanks for the quick answer though.

**Comment by thomaslevesque** [comment]
You're welcome. Good luck with the hooks!
