### ISSUE TITLE
Support for multiple key gestures

### ISSUE THREAD

**Issue by JobaDiniz** [thomaslevesque/NHotkey#7]
As in Visual Studio, `Ctrl+W,S` shows Solution Explorer. `Ctrl+K,Ctrl+D` formats the document.

It would be nice NHotKey to support these combinations. This [article](http://kent-boogaart.com/blog/multikeygesture) shows how this can be done in WPF with _InputGestures_, but it's not production ready.

**Comment by thomaslevesque** [comment]
Hi @JobaDiniz,

Thanks for the suggestion. It's an interesting idea, although it's probably not trivial to implement. I haven't touched this project in a long while and don't have much time to spend on it, but I'd be glad to accept contributions. If you want to give it a try, please discuss it here first to make sure we agree on the design.

**Comment by thomaslevesque** [comment]
Closing as "won't fix". If someone really wants this and steps up to work on this feature, I'll reconsider.
